# Generated by Django 5.2.17 on 2026-09-01 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_questions', models.JSONField(default=list)),
                ('resume_questions', models.JSONField(default=list)),
                ('behavioral_questions', models.JSONField(default=list)),
                ('topics_to_revise', models.JSONField(default=list)),
                ('interview_tips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_preparation', to='jobs.jobdescription')),
            ],
        ),
    ]
