# Generated by Django 5.2.17 on 2026-09-05 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_interviewpreparation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('total_questions', models.PositiveIntegerField(default=5)),
                ('current_question', models.PositiveIntegerField(default=1)),
                ('final_score', models.PositiveIntegerField(default=0)),
                ('communication_score', models.PositiveIntegerField(default=0)),
                ('technical_score', models.PositiveIntegerField(default=0)),
                ('relevance_score', models.PositiveIntegerField(default=0)),
                ('feedback', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='jobs.jobdescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('category', models.CharField(default='technical', max_length=50)),
                ('user_answer', models.TextField(blank=True, default='')),
                ('score', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True, default='')),
                ('better_answer', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobs.interviewsession')),
            ],
        ),
    ]
