# Generated by Django 5.2.17 on 2026-08-31 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_score', models.PositiveIntegerField(default=0)),
                ('professional_summary', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('suitable_roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='resumes.resume')),
            ],
        ),
    ]
